Configure basic CD

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,22 +17,22 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: JVM Setup
-        uses: ./.github/actions/jvm-setup
-
-      - name: Write env.properties
-        run: echo "${{ secrets.ENV_PROPERTIES }}" > ./env.properties
-
-      - name: Build
-        run: ./gradlew build
-
-      - name: Run tests
-        run: ./gradlew test
-
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v4
-        if: success() || failure()
-        with:
-          annotate_only: true
-          report_paths: "**/build/test-results/**/*.xml"
-          fail_on_failure: true
+#      - name: JVM Setup
+#        uses: ./.github/actions/jvm-setup
+#
+#      - name: Write env.properties
+#        run: echo "${{ secrets.ENV_PROPERTIES }}" > ./env.properties
+#
+#      - name: Build
+#        run: ./gradlew build
+#
+#      - name: Run tests
+#        run: ./gradlew test
+#
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@v4
+#        if: success() || failure()
+#        with:
+#          annotate_only: true
+#          report_paths: "**/build/test-results/**/*.xml"
+#          fail_on_failure: true
